dev:
  batch: 100
  name: "default"
  run_interval: 150
  fail_interval: 150
  verify_fail_interval: 150
  rate_limited_interval: 150
  model_path: "model-dev"
  tesseract_path: "D:/soft/tesseractocr/tesseract.exe"
  # db or excel
  write_token_to: "db"
  prompt_first: "no"
  # jg 极光 v v2rayN
  vpn: "jg"
  db:
    host: "192.168.101.130"
    user: "root"
    password: "mysql"
    database: "autorunmj"

prod:
  batch: 30
  name: "default"
  run_interval: 130
  fail_interval: 110
  verify_fail_interval: 130
  rate_limited_interval: 130
  model_path: "model"
  tesseract_path: "C:/dev/Tesseract-OCR/tesseract.exe"
  # db or excel
  write_token_to: "db"
  prompt_first: "yes"
  vpn: "v"
  db:
    host: "192.168.101.130"
    user: "root"
    password: "mysql"
    database: "autorunmj"

prod-1:
  batch: 30
  name: "default"
  run_interval: 130
  fail_interval: 130
  verify_fail_interval: 130
  rate_limited_interval: 130
  model_path: "model-1"
  tesseract_path: "C:/dev/Tesseract-OCR/tesseract.exe"
  # db or excel
  write_token_to: "db"
  prompt_first: "yes"
  vpn: "v"
  db:
    host: "192.168.101.130"
    user: "root"
    password: "mysql"
    database: "autorunmj"