dev:
  batch: 10
  name: "default"
  run_interval: 130
  fail_interval: 130
  verify_fail_interval: 130
  rate_limited_interval: 130
  model_path: "model-dev"
  tesseract_path: "D:/soft/tesseractocr/tesseract.exe"
  db:
    host: "192.168.73.129"
    user: "root"
    password: "mysql"
    database: "autorunmj"

prod:
  batch: 20
  name: "default"
  run_interval: 130
  fail_interval: 110
  verify_fail_interval: 130
  rate_limited_interval: 130
  model_path: "model"
  tesseract_path: "C:/dev/Tesseract-OCR/tesseract.exe"
  db:
    host: "192.168.73.129"
    user: "root"
    password: "mysql"
    database: "autorunmj"

prod-1:
  batch: 20
  name: "default"
  run_interval: 110
  fail_interval: 130
  verify_fail_interval: 130
  rate_limited_interval: 130
  model_path: "model-1"
  tesseract_path: "C:/dev/Tesseract-OCR/tesseract.exe"
  db:
    host: "192.168.73.129"
    user: "root"
    password: "mysql"
    database: "autorunmj"